# Generated by Django 3.2.3 on 2022-05-06 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuitionapp', '0002_alter_student_parentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='simage',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='simage'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='timage',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/', verbose_name='timage'),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='questionpaper',
            field=models.ImageField(blank=True, null=True, upload_to='qpaper/', verbose_name='questionpaper'),
        ),
    ]
