# Generated by Django 3.2.3 on 2022-05-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0003_auto_20220506_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='you',
        ),
    ]
