# Generated by Django 3.2.3 on 2022-05-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0004_rename_user_student_you'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='you',
            new_name='user',
        ),
    ]
