# Generated by Django 3.2.3 on 2022-05-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0005_rename_you_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='Grade',
        ),
        migrations.AddField(
            model_name='userclass',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuitionapp.tutor'),
        ),
    ]
